### ISSUE TITLE
Add link to Columbus forum

### ISSUE THREAD

**Issue by saelili** [FCCColumbus/fcc-columbus#101]
We have a link to the the free Code Camp forum on our home page in the Useful Links section. Now that free Code Camp Columbus has it's own sub-forum we should also have a link to direct users there. An additional link, icon, and description should be added to that section.

https://www.freecodecamp.org/forum/c/united-states-study-groups/columbus

**Comment by katherine95** [comment]
@saelili is this issue still up for grab?

**Comment by Kavinci** [comment]
@katherine95, yes it is.

**Comment by DanStockham** [comment]
The sub forum no longer exists on the Free Code Camp forum.
